name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile 
      run: |
        echo '#include "LightCPP.hpp"
        int main() { return 0; }' > test.cpp
        g++ -std=c++20 -Wall test.cpp -o test_app
      
